# Generated by Django 3.2.15 on 2023-03-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sName', models.CharField(max_length=20)),
                ('sSex', models.CharField(default='N', max_length=2)),
                ('sBrithday', models.DateField()),
                ('sEmail', models.EmailField(blank=True, default='', max_length=50)),
                ('sPhone', models.CharField(blank=True, default='', max_length=20)),
                ('sAddress', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
